#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: Rust

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest] # Note: windows not supported because of cyclocut not ported

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup show
          rustup component add rustfmt clippy

      - name: Code format check
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --all --examples -- -D warnings

      - name: Build zenoh-plugin-mqtt
        run: cargo build -p zenoh-plugin-mqtt --verbose --all-targets

      - name: Build zenoh-bridge-mqtt
        run: cargo build -p zenoh-bridge-mqtt --verbose --all-targets

      - name: Run tests
        run: cargo test --verbose
